### ISSUE TITLE
[Safari] - How It Works slider glows different colours

### ISSUE THREAD

**Issue by celineselee** [StarterHacks/sh-site#33]
<img width="369" alt="screenshot_2018-11-14__7_34_pm" src="https://user-images.githubusercontent.com/25260228/48521853-52d65b00-e844-11e8-9322-240bdc0472ef.png">

It also glows blue after you resize the screen
<img width="467" alt="screenshot_2018-11-14__7_41_pm" src="https://user-images.githubusercontent.com/25260228/48522093-4bfc1800-e845-11e8-89ae-e088ee523c1a.png">

I can't figure out exactly when this actually happens

**Comment by ahrarmonsur** [comment]
@celineselee, LOL this was a hilarious issue. It was because when defining the box shadow, Kristy used rgb(0, 0, 0, 0.5) instead of rgbA(0, 0, 0, 0.5).

Chrome is smart enough to figure out what we wanted, but Safari wasn't and it errored, resulting in the drop shadow color not being set.

The fix for this also coincidentally fixed all the ugly super dark drop shadows!

GREAT BUG! :D
